### ISSUE TITLE
question

### ISSUE THREAD

**Issue by camhart** [coredns/rrl#18]
Why is `ipv4-prefix-length` and `ipv6-prefix-length` set to defaults `24` and `56`?  What's the rationale there?

I know these are the BIND defaults.  I can't seem to find any explanation though.  Just working it backwords, one guess I have is that you assume "organizations" (like AWS for example) own entire blocks of IP addresses.  That way by setting the prefix length to less than `32/64` you'd be "protecting" all of that organization's servers "better".

**Comment by chrisohaver** [comment]
> I know these are the BIND defaults.

Yes, thats why.  I just replicated the defaults, deferring to the wisdom of the BIND RRL authors, but also to make the feature more familiar to those familiar with BIND's RRL.

I suspect part of it is that smaller buckets means more total buckets, which in turn means a bigger memory footprint.
