### ISSUE TITLE
example

### ISSUE THREAD

**Issue by balboah** [coredns/rrl#20]
Hi,

I added this plugin in the end of plugins.cfg and have set
```
rrl . {
    responses-per-second 1
  }
```

I was expecting no result when simply running a couple of dig commands simultaneously, but it was all fine.
How can I confirm that the plugin works as expected?

**Comment by chrisohaver** [comment]
>I added this plugin in the end of plugins.cfg

rrl needs to be near the top of the plugin.cfg plugin list.

**Comment by balboah** [comment]
Good hint, basically before cache plugin if you're looking at the default list of plugins?
However I figured out that I didn't actually query the updated server, so it's all working as I expected even when I have the plugin in the end

**Comment by chrisohaver** [comment]
Ah - yes, if no plugins in the Corefile provide an answer, then CoreDNS returns a SERVFAIL by default.  In that case even if _rrl_ is at the end of the plugin list, limits should be enforced since the entire plugin chain is traversed.

I should update the example in the README to be more practical.
