### ISSUE TITLE
Response Truncation (slip-ratio)

### ISSUE THREAD

**Issue by lara** [coredns/rrl#32]
hey there, are there any plans to provide an option to truncate responses instead of dropping them?

**Comment by chrisohaver** [comment]
It's identified in the design spec, https://github.com/coredns/rrl/blob/master/README-DEV.md#slip-ratio, but it is not implemented, no work has begun on it.

Is this something you want to implement? If not, I can start on it.

**Comment by lara** [comment]
oh nice, I missed that. I'd be happy to work on it.

**Comment by chrisohaver** [comment]
@lara, have you had time begin on this yet?  If not, I can probably knock it out pretty quickly.

**Comment by chrisohaver** [comment]
@lara, please see #35, for my implementation of this feature.

**Comment by lara** [comment]
@chrisohaver thank you for implementing the feature, life got in the way for me
